Fix "use after closing" error when calling pool.getResource()
There exists race condition between pool.close() and pool.getResource(), which may cause the following exception：
   redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at io.codis.jodis.RoundRobinJedisPool.getResource(RoundRobinJedisPool.java:220)
	...

I proposed two solutions to this problem:
   1. defer "close" of a pool; 2. close the pool when PooledObject.finalize() is called
   
The first solution may cause errors under conditions that are rarely happen, but it is more deterministic than the second on resource collection. I prefer the first one.